version: '3.4'

services:
  aspnetredis:
    image: aspnetredis
    build:
      context: .
      dockerfile: AspNetRedis/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    environment:
      - "REDIS_HOST=host"
      - "REDIS_PORT=13329"
      - "REDIS_PASSWORD=password"
